
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNdddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms:/hdddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy++yo--odddddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+..+dddh:.:ydddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmMMMmmMMMMMMMmhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+-..```-ydddo..shhhddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/./o` `+-  :MMd/:`  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMNmo.````````+dho/oyhhho/ydddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. /MMm++dh++dMMMMM-  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmh-```   ``:+yhhhs:.``.+hddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs  /MMMMMMMMMMMMMMM-  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMdhhdmmmmd/`   `/syyhs/.```````:ydddNMMMMMMMMMMMMMMMN+-:/:-+dMMNds+:.mo:..:sMMMMMMho:.../ohNMMmhs/-+h+-../dMMN//-  .///sMdyo:-MMMMM-  yMMMMNh/-..:+dMMMMN+-:/://yMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMdhhhmmmmmy.:oyyys+-```````````.odddmMMMMMMMMMMMMMs  -MMM/  yMmso   -ohy-  :MMMd. -mMMNo  `yMhs:  `:sds`  yMMMMs  /MMMMys/  .MMMMM-  yMMMh`.hMMd-  :NMN` sMMMy`+MMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMmhhhdmmdhyyyy+:.....```````````:hddmNMMMMMMMMMMMd--yMMm:  sMMMm   MMMMm   MMd  `mMMMMMs   hMMs  /MMMMo  /MMMMs  /MMMMMMd  .MMMMM-  yMMh` +ssss+   sMh  .smMMshMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhhhyyyo:..........``````````.odydmMMMMMMMMMMMMdo:-+-  sMMMm   MMMMm   MMo  -MMMMMMN-  :MMs  /MMMMs  /MMMMs  /MMMMMMd  .MMMMM-  yMM:  hddddddddNMMh-   ./hMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhys-.............```````````:hmNMMMMMMMMMMy. /mMM/  sMMMm   MMMMm   MMy  `mMMMMMM/  +MMs  /MMMMs  /MMMMs  /MMMMMMd  .MMMMM-  yMM:  sMMMMMMMMdMNdMmy:   -NMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhyo-.............````````.+hMMMMMMMMMMMMd`  yMMM:  sMMMm   MMMMm   MMN.  :NMMMMN` `NMMs  /MMMMs  /MMMMs  /MMMMMMd  .MMMMM-  yMMh`  omMMMMy.+My hMMMM+  sMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhy/..............```./yNMMMMMMMMMMMMMMm-  `::-:  `::ds   dNMm+   dMMMs` :ymNy. /NMMd:  -mMMd:  -mMNd:  .hNMMMm/  `dNMNh.  oNMMh-   `:.`.sMMy `odNm/ -mMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+--:yhhho-.............--./sMMMMMMMMMMMMMMMMMhs+shMMhoshmsssssssdsssssshMMMNho///oyNMMMmssssssyhssssssdsssssssshMysssssssdsssssssdMMMhs///sdMMMMmshs+/+smMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMNy:   .+:`/yhhy:........--`+ds.  ./hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMNNMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMNNMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMNy.  -smMd`   .:oyo-..::--`   oMMd+`  /hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMNNmhs/-   -hMMMMd`       -dms`       oNMMMNs`  .ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMddsso//-.`    `-+ymMMMMMMm`      -NMMMy`       :MMMMMNy/`   ../+shddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMN/`   `.-:/+syhmNMMMMMMMMMMM-      -mdNMMmd`      `NMMMMMMMMmhs+/-.`       --/hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMM-  /dNNMMMMMMMMMMMMMMMMMMMMs      -y. +Mh /y      `NMMMMMMMMMMMMMMMNmdhyyss+.  .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMm  :MMMMMMMMMMMMMMMMMMMMMMMM-      -   yMN. .:     .NMMMMMMMMMMMMMMMMMMMMMMMMMs  :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMM/  hMMMMMMMMMMMMMMMMMMMMMMMN.         :NMMo        :MMMMMMMMMMMMMMMMMMMMMMMMMMM: `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMh  :MMMMMMMMMMMMMMMMMMMMMMMMN`        `dMMMm`       +MMMMMMMMMMMMMMMMMMMMMMMMMMMo  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MM:  hMMMMMMMMMMMMMMMMMMMMMMMMM:        :MMMMM/       hMMMMMMMMMMMMMMMMMMMMMMMMMMMh  +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#Md` :MMMMMMMMMMMMMMMMMMMMMMMMMMs        oMMMMMh      .NMMMMMMMMMMMMMMMMMMMMMMMMMMMN` -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#M+  yMMMMMMMMMMMMMMMMMMMMMMMMMMN.       sMMMMMN`     +MMMMMMMMMMMMMMMMMMMMMMMMMMMMM: `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#N` .MMMMMMMMMMMMMMMMMMMMMMMMMMMMy       yMMMMMM-    `dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo  dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#h  /MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+      dMMMMMM/    /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh   sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#  .+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/     mMMMMMM/   `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh. `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#  .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/    NMMMMMM+   sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:  +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#  /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+   NMMMMMMo  +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd. /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

import os,sys
from tkinter import Tk
from tkinter.filedialog import askopenfilename

logo = """#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNdddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms:/hdddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy++yo--odddddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+..+dddh:.:ydddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+-..```-ydddo..shhhddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmo.````````+dho/oyhhho/ydddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmh-```   ``:+yhhhs:.``.+hddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMdhhdmmmmd/`   `/syyhs/.```````:ydddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMdhhhmmmmmy.:oyyys+-```````````.odddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhdmmdhyyyy+:.....```````````:hddmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhhhyyyo:..........``````````.odydmMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhys-.............```````````:hmNMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhyo-.............````````.+hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhy/..............```./yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+--:yhhho-.............--./sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMNy:   .+:`/yhhy:........--`+ds.  ./hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMNy.  -smMd`   .:oyo-..::--`   oMMd+`  /hMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMNNmhs/-   -hMMMMd`       -dms`       oNMMMNs`  .ohNMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMddsso//-.`    `-+ymMMMMMMm`      -NMMMy`       :MMMMMNy/`   ../+shddMMMMMMMMMMMMMMMM\nMMMMN/`   `.-:/+syhmNMMMMMMMMMMM-      -mdNMMmd`      `NMMMMMMMMmhs+/-.`       --/hNMMMMMMM\nMMMM-  /dNNMMMMMMMMMMMMMMMMMMMMs      -y. +Mh /y      `NMMMMMMMMMMMMMMMNmdhyyss+.  .NMMMMMM\nMMMm  :MMMMMMMMMMMMMMMMMMMMMMMM-      -   yMN. .:     .NMMMMMMMMMMMMMMMMMMMMMMMMMs  :MMMMMM\nMMM/  hMMMMMMMMMMMMMMMMMMMMMMMN.         :NMMo        :MMMMMMMMMMMMMMMMMMMMMMMMMMM: `mMMMMM\nMMh  :MMMMMMMMMMMMMMMMMMMMMMMMN`        `dMMMm`       +MMMMMMMMMMMMMMMMMMMMMMMMMMMo  yMMMMM\nMM:  hMMMMMMMMMMMMMMMMMMMMMMMMM:        :MMMMM/       hMMMMMMMMMMMMMMMMMMMMMMMMMMMh  +MMMMM\nMd` :MMMMMMMMMMMMMMMMMMMMMMMMMMs        oMMMMMh      .NMMMMMMMMMMMMMMMMMMMMMMMMMMMN` -MMMMM\nM+  yMMMMMMMMMMMMMMMMMMMMMMMMMMN.       sMMMMMN`     +MMMMMMMMMMMMMMMMMMMMMMMMMMMMM: `mMMMM\nN` .MMMMMMMMMMMMMMMMMMMMMMMMMMMMy       yMMMMMM-    `dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo  dMMMM\nh  /MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+      dMMMMMM/    /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh   sMMM\n  .+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/     mMMMMMM/   `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh. `MMM\n  .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/    NMMMMMM+   sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:  +MMM\n  /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+   NMMMMMMo  +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd. /MMM\n"""
print(logo)
# ABRE FICHERO
Tk().withdraw()
#filename = askopenfilename() 
filename = askopenfilename(title="Anonfile Upload File",filetypes=[
	("Text files","*.txt"),
	("Parthenoun files","*.pth"),])
#SUBE FICHERO
result = os.system('curl -s -F "file=@'+filename+'" https://api.anonfiles.com/upload > a.bt ')
#resultat = result.replace('"full"','FULL')
#print(resultat)
#print(result)

fina = "a.bt"

char1 = '{"status":true,"data":{"file":{"url":{"full":"'
char2 = 'FULL URL: '
char3 = '","short":"'
char4 = '\nSHORT URL: '
char5 = '"},"metadata":{"id":"'
char6 = '\n'

filer = open(fina, "r")
filew = open(fina+'t', "w")

buff = filer.read()
rbuff = buff.replace(char1, char2)
rbuff = rbuff.replace(char3, char4)
rbuff = rbuff.replace(char5, char6)
andale = os.system('cat a.btt')

filew.write(rbuff)

filer.close()
filew.close()

"""
filen = open(fina+'t',"r")
nono = filen.readline()
nono = filen.readline(1)
for line in filen:
	print(line)
"""
nono = os.system('head '+fina+'t -n 2 > '+fina)
filen = open(fina, "r")
buffre = filen.read()
print(buffre)
filen.close()
#nono = nono.replace("FULL","AUX")
os.remove(fina)
try:
	os.remove(fina+'t')
except:
	a = 'a'
try:
	os.remove(fina)
except:
	a = 'a'
#print(nono)
#print(content)
#"""{"status":true,"data":{"file":{"url":{"full":"https://anonfiles.com/L2z7J05ep8/a_txt","short":"https://anonfiles.com/L2z7J05ep8"},"metadata":{"id":"L2z7J05ep8","name":"a.txt","size":{"bytes":0,"readable":"0 Bytes"}}}}}"""

#EXTRAE EL URL
