from colorama import init, Fore, Back, Style

init(convert=True)

print(Fore.WHITE)
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNdddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms:/hdddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy++yodddddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+..+dddh:.:ydddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmMMMmmMMMMMMMmhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+-..```-ydddo..shhhddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/./o` `+-  :MMd/:`  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMNmo.````````+dho/oyhhho/ydddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. /MMm++dh++dMMMMM-  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmh-```   ``:+yhhhs:.``.+hddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs  /MMMMMMMMMMMMMMM-  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMdhhdmmmmd/`   `/syyhs/.```````:ydddNMMMMMMMMMMMMMMMN+-:/:-+dMMNds+:.mo:..:sMMMMMMho:.../ohNMMmhs/-+h+-../dMMN//-  .///sMdyo:-MMMMM-  yMMMMNh/-..:+dMMMMN+-:/://yMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMdhhhmmmmmy.:oyyys+-```````````.odddmMMMMMMMMMMMMMs  -MMM/  yMmso   -ohy-  :MMMd. -mMMNo  `yMhs:  `:sds`  yMMMMs  /MMMMys/  .MMMMM-  yMMMh`.hMMd-  :NMN` sMMMy`+MMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMmhhhdmmdhyyyy+:.....```````````:hddmNMMMMMMMMMMMyMMm:  sMMMm   MMMMm   MMd  `mMMMMMs   hMMs  /MMMMo  /MMMMs  /MMMMMMd  .MMMMM-  yMMh` +ssss+   sMh  .smMMshMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhhhyyyo:..........``````````.odydmMMMMMMMMMMMMdo:-+-  sMMMm   MMMMm   MMo  -MMMMMMN-  :MMs  /MMMMs  /MMMMs  /MMMMMMd  .MMMMM-  yMM:  hddddddddNMMh-   ./hMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhys-.............```````````:hmNMMMMMMMMMMy. /mMM/  sMMMm   MMMMm   MMy  `mMMMMMM/  +MMs  /MMMMs  /MMMMs  /MMMMMMd  .MMMMM-  yMM:  sMMMMMMMMdMNdMmy:   -NMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhyo-.............````````.+hMMMMMMMMMMMMd`  yMMM:  sMMMm   MMMMm   MMN.  :NMMMMN` `NMMs  /MMMMs  /MMMMs  /MMMMMMd  .MMMMM-  yMMh`  omMMMMy.+My hMMMM+  sMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhy/..............```./yNMMMMMMMMMMMMMMm-  `::-:  `::ds   dNMm+   dMMMs` :ymNy. /NMMd:  -mMMd:  -mMNd:  .hNMMMm/  `dNMNh.  oNMMh-   `:.`.sMMy `odNm/ -mMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMNh:yhhho-............./sMMMMMMMMMMMMMMMMMhs+shMMhoshmsssssssdsssssshMMMNho///oyNMMMmssssssyhssssssdsssssssshMysssssssdsssssssdMMMhs///sdMMMMmshs+/+smMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMNy:   .+:`/yhhy:.......`+ds.  ./hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMNNMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMNNMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMNy.  -smMd`   .:oyo-..:`   oMMd+`  /hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMNNmhs/-   -hMMMMd`       -dms`       oNMMMNs`  .ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMddsso//-.`    `-+ymMMMMMMm`      -NMMMy`       :MMMMMNy/`   ../+shddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMN/`   `.-:/+syhmNMMMMMMMMMMM-      -mdNMMmd`      `NMMMMMMMMmhs+/-.`      /hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMM-  /dNNMMMMMMMMMMMMMMMMMMMMs      -y. +Mh /y      `NMMMMMMMMMMMMMMMNmdhyyss+.  .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMm  :MMMMMMMMMMMMMMMMMMMMMMMM-      -   yMN. .:     .NMMMMMMMMMMMMMMMMMMMMMMMMMs  :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMM/  hMMMMMMMMMMMMMMMMMMMMMMMN.         :NMMo        :MMMMMMMMMMMMMMMMMMMMMMMMMMM: `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMh  :MMMMMMMMMMMMMMMMMMMMMMMMN`        `dMMMm`       +MMMMMMMMMMMMMMMMMMMMMMMMMMMo  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MM:  hMMMMMMMMMMMMMMMMMMMMMMMMM:        :MMMMM/       hMMMMMMMMMMMMMMMMMMMMMMMMMMMh  +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#Md` :MMMMMMMMMMMMMMMMMMMMMMMMMMs        oMMMMMh      .NMMMMMMMMMMMMMMMMMMMMMMMMMMMN` -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#M+  yMMMMMMMMMMMMMMMMMMMMMMMMMMN.       sMMMMMN`     +MMMMMMMMMMMMMMMMMMMMMMMMMMMMM: `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#N` .MMMMMMMMMMMMMMMMMMMMMMMMMMMMy       yMMMMMM-    `dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo  dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#h  /MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+      dMMMMMM/    /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh   sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#  .+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/     mMMMMMM/   `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh. `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#  .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/    NMMMMMM+   sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:  +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#  /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+   NMMMMMMo  +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd. /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
import os,sys
from tkinter import Tk
from tkinter.filedialog import askopenfilename
os.system('title Anonfile Uploader by J0rd1s3rr4n0')
logo = """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNdddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms:/hdddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy++yodddddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+..+dddh:.:ydddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+-..```-ydddo..shhhddddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmo.````````+dho/oyhhho/ydddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmh-```   ``:+yhhhs:.``.+hddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMdhhdmmmmd/`   `/syyhs/.```````:ydddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMdhhhmmmmmy.:oyyys+-```````````.odddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhdmmdhyyyy+:.....```````````:hddmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhhhyyyo:..........``````````.odydmMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhys-.............```````````:hmNMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhyo-.............````````.+hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhy/..............```./yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh:yhhho-............./sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMNy:   .+:`/yhhy:.......`+ds.  ./hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMNy.  -smMd`   .:oyo-..:`   oMMd+`  /hMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMNNmhs/-   -hMMMMd`       -dms`       oNMMMNs`  .ohNMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMddsso//-.`    `-+ymMMMMMMm`      -NMMMy`       :MMMMMNy/`   ../+shddMMMMMMMMMMMMMMMM\nMMMMN/`   `.-:/+syhmNMMMMMMMMMMM-      -mdNMMmd`      `NMMMMMMMMmhs+/-.`      /hNMMMMMMM\nMMMM-  /dNNMMMMMMMMMMMMMMMMMMMMs      -y. +Mh /y      `NMMMMMMMMMMMMMMMNmdhyyss+.  .NMMMMMM\nMMMm  :MMMMMMMMMMMMMMMMMMMMMMMM-      -   yMN. .:     .NMMMMMMMMMMMMMMMMMMMMMMMMMs  :MMMMMM\nMMM/  hMMMMMMMMMMMMMMMMMMMMMMMN.         :NMMo        :MMMMMMMMMMMMMMMMMMMMMMMMMMM: `mMMMMM\nMMh  :MMMMMMMMMMMMMMMMMMMMMMMMN`        `dMMMm`       +MMMMMMMMMMMMMMMMMMMMMMMMMMMo  yMMMMM\nMM:  hMMMMMMMMMMMMMMMMMMMMMMMMM:        :MMMMM/       hMMMMMMMMMMMMMMMMMMMMMMMMMMMh  +MMMMM\nMd` :MMMMMMMMMMMMMMMMMMMMMMMMMMs        oMMMMMh      .NMMMMMMMMMMMMMMMMMMMMMMMMMMMN` -MMMMM\nM+  yMMMMMMMMMMMMMMMMMMMMMMMMMMN.       sMMMMMN`     +MMMMMMMMMMMMMMMMMMMMMMMMMMMMM: `mMMMM\nN` .MMMMMMMMMMMMMMMMMMMMMMMMMMMMy       yMMMMMM-    `dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo  dMMMM\nh  /MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+      dMMMMMM/    /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh   sMMM\n  .+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/     mMMMMMM/   `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh. `MMM\n  .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/    NMMMMMM+   sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:  +MMM\n  /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+   NMMMMMMo  +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd. /MMM\n"""
print(logo)
Tk().withdraw()
filename = askopenfilename(title="Anonfile Upload File",filetypes=[
	("All files","*.*"),])
try:
	os.system('title Anonfile Uploader by J0rd1s3rr4n0 ~ [ STATUS: UPLOADING ]')
	result = os.system('curl -s -F "file=@'+filename+'" https://api.anonfiles.com/upload > a.bt ')
	os.system('title Anonfile Uploader by J0rd1s3rr4n0 ~ [ STATUS: UPLOADED, DOWNLOADING RESOURCES...]')
	fina = "a.bt"
	char1 = '{"status":true,"data":{"file":{"url":{"full":"'
	char2 = 'FULL URL: '
	char3 = '","short":"'
	char4 = '\nSHORT URL: '
	char5 = '"},"metadata":{"'
	char6 = '\n'
	char7 = 'id":"'
	char8 = '\n[ FILE INFO ]\nID: '
	char9 = '","name":"'
	char10= '\nFILE NAME: '
	char11= '","size":{'
	char12= '\nSIZE: '
	char13= '"bytes":'
	char14= '\n	BYTES: '
	char15= ',"readable":"'
	char16= '\n	REDEABLE: '
	char17= '"}}}}}'
	char18= '\n'
	char19= '{"status":false,"error":{"message":"No file chosen.","type":"ERROR_FILE_NOT_PROVIDED","code":10}}'
	char20= ' [ ERROR, NO SE SELECIONO NINGUN ARCHIVO ] \n'
	filer = open(fina, "r")
	filew = open(fina+'t', "w")
	buff = filer.read()
	rbuff = buff.replace(char1, char2)
	rbuff = rbuff.replace(char3, char4)
	rbuff = rbuff.replace(char5, char6)
	rbuff = rbuff.replace(char7, char8)
	rbuff = rbuff.replace(char9, char10)
	rbuff = rbuff.replace(char11, char12)
	rbuff = rbuff.replace(char13, char14)
	rbuff = rbuff.replace(char15, char16)
	rbuff = rbuff.replace(char17, char18)
	rbuff = rbuff.replace(char19, char20)

	andale = os.system('type a.btt')
	filew.write(rbuff)
	filer.close()
	filew.close()
	nono = os.system('type '+fina+'t > '+fina)
	filen = open(fina, "r")
	buffre = filen.read()
	print(buffre)
	filen.close()
	os.remove(fina)
	os.system('title Anonfile Uploader by J0rd1s3rr4n0 ~ [ WAITING TO CLOSE ]')
except:
	os.system('title Anonfile Uploader by J0rd1s3rr4n0 ~ [ ERROR, WE CAN NOT UPLAOD YOUR FILE')
	print('ERROR')
try:
	os.remove(fina+'t')
except:
	a = 'a'
try:
	os.remove(fina)
except:
	a = 'a'
print('\nEN 5 MINUTOS SE CERRARA LA VENATANA')
os.system('timeout /t 500 > %TEMP%/null')